CREATE DATABASE Tazeez 
GO

USE [Tazeez]
GO

CREATE TABLE [dbo].[User] (
 [Id] INT CHECK ([Id] > 0) NOT NULL IDENTITY,
  [FirstName] VARCHAR(255) NOT NULL DEFAULT '',
  [LastName] VARCHAR(225) NOT NULL DEFAULT '',
  [Email] VARCHAR(255) NOT NULL DEFAULT '',
  [PhoneNumber] VARCHAR(45) NOT NULL DEFAULT '',
  [Password] VARCHAR(255) NOT NULL DEFAULT '',
  [City] VARCHAR(45) NOT NULL DEFAULT '',
  [Image] VARCHAR(500) NOT NULL DEFAULT '',
  [CreatedDate] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
  [UpdateDate] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
  [Archived] SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ([Id]),
  CONSTRAINT [Id_UNIQUE] UNIQUE ([Id] ASC),
  CONSTRAINT [Email_UNIQUE] UNIQUE ([Email] ASC));
