CREATE TABLE `tazeez`.ContactRequestModel (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(255) NOT NULL DEFAULT '',
  `Email` VARCHAR(255) NOT NULL DEFAULT '',
  `PhoneNumber` VARCHAR(45) NOT NULL DEFAULT '',
  `Message` text NOT NULL,
  `CreatedDate` timestamp not NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdateDate` timestamp not NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Archived` tinyint(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  CONSTRAINT `Id_UNIQUE` UNIQUE (`Id` ASC));