CREATE TABLE `tazeez`.`doctor` (
  `Id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Specialist` VARCHAR(500) NULL,
  `Description` TEXT NULL,
  `UserId` INT(11) NOT NULL,
  `CreatedUTC` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedUTC` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Archived` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `Doctor_UserId_idx` (`UserId` ASC),
  CONSTRAINT `Doctor_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `tazeez`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);