

export enum AuthActionTypesEnum {
    AUTH_LOG_IN = 'AUTH_LOG_IN',
    AUTH_LOG_IN_SUCCESS = 'AUTH_LOG_IN_SUCCESS',
    AUTH_LOG_IN_FAILURE = 'AUTH_LOG_IN_FAILURE',
 
    AUTH_LOG_OUT = 'AUTH_LOG_OUT',
    AUTH_LOG_OUT_SUCCESS = 'AUTH_LOG_OUT_SUCCESS',
    AUTH_LOG_OUT_FAILURE = 'AUTH_LOG_OUT_FAILURE',
 
    AUTH_SIGN_UP = 'AUTH_SIGN_UP',
    AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS',
    AUTH_SIGN_UP_FAILURE = 'AUTH_SIGN_UP_FAILURE',
 }
